version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "3000:3000"
    volumes:
      - ./:/backend
    depends_on:
      - fileserver
  fileserver:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=qwer1234
    volumes: 
      - ./file:/data
    command: server /data --console-address ":9001"